// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Contexts;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105113502_structure")]
    partial class structure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Elektronik ürünler",
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bilgisayar ve aksesuarları",
                            Name = "Bilgisayar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Akıllı telefonlar",
                            Name = "Telefon"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Beyaz eşya ve küçük ev aletleri",
                            Name = "Ev Aletleri"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kitap ve dergiler",
                            Name = "Kitap"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kadın ve erkek giyim",
                            Name = "Giyim"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Spor ve klasik ayakkabılar",
                            Name = "Ayakkabı"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Spor malzemeleri",
                            Name = "Spor"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Kozmetik ve kişisel bakım",
                            Name = "Kozmetik"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Çocuk oyuncakları",
                            Name = "Oyuncak"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Deneme verisi",
                            Name = "Deneme"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Ev dekorasyonu ve mobilyalar",
                            Name = "Mobilya"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
